create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  stock integer not null default 0,
  cover text,
  ebook text,
  ebook_type text
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null,
  role text not null default 'client'
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  borrower text not null,
  book_id bigint,
  title text not null,
  status text not null default 'Dipinjam'
);

alter table public.books enable row level security;
alter table public.users enable row level security;
alter table public.transactions enable row level security;

create policy "books_select_all" on public.books for select using (true);
create policy "books_insert_all" on public.books for insert with check (true);
create policy "books_update_all" on public.books for update using (true) with check (true);
create policy "books_delete_all" on public.books for delete using (true);

create policy "users_select_all" on public.users for select using (true);
create policy "users_insert_all" on public.users for insert with check (true);
create policy "users_update_all" on public.users for update using (true) with check (true);
create policy "users_delete_all" on public.users for delete using (true);

create policy "transactions_select_all" on public.transactions for select using (true);
create policy "transactions_insert_all" on public.transactions for insert with check (true);
create policy "transactions_update_all" on public.transactions for update using (true) with check (true);
create policy "transactions_delete_all" on public.transactions for delete using (true);
